services:
  - type: web
    name: order-tracking
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_orders,write_app_proxy
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SHOPIFY_STORE_DOMAIN
        value: fjcompany-uiwwlhq5.myshopify.com
      - key: FEDEX_ENVIRONMENT
        value: sandbox
      - key: FEDEX_CLIENT_ID
        sync: false
      - key: FEDEX_CLIENT_SECRET
        sync: false
      - key: FEDEX_ACCOUNT_NUMBER
        sync: false
      - key: LEOPARDS_API_URL
        sync: false
      - key: LEOPARDS_API_USERNAME
        sync: false
      - key: LEOPARDS_API_PASSWORD
        sync: false